#!/bin/bash

# This script creates a tar.gz package with the files of this quest.
# Usage: ./make_quest_package quest_name version_number

if [ $# != 2 ];
then
  echo "Usage: $0 quest_name version_number"
  exit 1
fi

quest="$1"
version="$2"

rm -rf "${quest}-${version}"
mkdir "${quest}-${version}"
git archive -o "${quest}-${version}/tmp.tar" HEAD data ChangeLog CMakeLists.txt readme.txt make_quest_package make_zip
cd "${quest}-${version}"
tar xf tmp.tar
rm tmp.tar
cd ..
rm -f "${quest}-${version}.tar.gz"
tar czf "${quest}-${version}.tar.gz" "${quest}-${version}"
rm -rf "${quest}-${version}"

